#!/usr/bin/python3
import RPi.GPIO as GPIO
import time
import Adafruit_DHT

GPIO.setwarnings(False)
GPIO.cleanup()
GPIO.setmode(GPIO.BCM)

MOSFET = 17
DHT_PIN = 4

GPIO.setup(MOSFET, GPIO.OUT)
DHT_SENSOR = Adafruit_DHT.DHT22

print ("System On")


def get_temp():
    while True:
        humidity, temperature = Adafruit_DHT.read_retry(DHT_SENSOR, DHT_PIN)

        if humidity is not None and temperature is not None:
            print("Temp={0:0.1f}*C  Humidity={1:0.1f}%".format(temperature, humidity))
            return temperature
        else:
            print("Failed to retrieve data from DHT22")


while True:
    temperature=get_temp()
    time.sleep(10)
    if temperature >= 0:
        GPIO.output(17, GPIO.HIGH)
        print ("heat is on")
    else:
        print ("heat not on")
