#!/usr/bin/python3
import RPi.GPIO as GPIO
import time
import Adafruit_DHT

MOSFET = 17
DHT_PIN = 4

GPIO.setmode(GPIO.BCM)
GPIO.setup(MOSFET, GPIO.OUT)
DHT_SENSOR = Adafruit_DHT.DHT22

print ("System On")

while True:
    humidity, temperature = Adafruit_DHT.read_retry(DHT_SENSOR, DHT_PIN)

    if humidity is not None and temperature is not None:
        print("Temp={0:0.1f}*C  Humidity={1:0.1f}%".format(temperature, humidity))
    else:
        print("Failed to retrieve data from DHT22")

    if temperature > 0:
        GPIO.output(17, GPIO.HIGH)
        print ("Heating on")
    else:
        print ("Temperature okay")
